// <auto-generated />
using GymTracker.Infrastructure.Data;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace GymTracker.Infrastructure.Migrations
{
    [DbContext(typeof(GymDbContext))]
    [Migration("20260925123528_InitialCreate")]
    partial class InitialCreate
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder.HasAnnotation("ProductVersion", "10.0.12");

            modelBuilder.Entity("GymTracker.Core.Models.Exercise", b =>
                {
                    b.Property<string>("Id")
                        .HasColumnType("TEXT")
                        .HasJsonPropertyName("id");

                    b.PrimitiveCollection<string>("Apparatus")
                        .IsRequired()
                        .HasColumnType("TEXT")
                        .HasJsonPropertyName("apparatus");

                    b.Property<string>("BodyPart")
                        .IsRequired()
                        .HasColumnType("TEXT")
                        .HasJsonPropertyName("bodyPart");

                    b.Property<double>("CaloriesPerMinute")
                        .HasColumnType("REAL")
                        .HasJsonPropertyName("caloriesPerMinute");

                    b.Property<string>("Category")
                        .IsRequired()
                        .HasColumnType("TEXT")
                        .HasJsonPropertyName("category");

                    b.Property<string>("Description")
                        .IsRequired()
                        .HasColumnType("TEXT")
                        .HasJsonPropertyName("description");

                    b.Property<string>("Difficulty")
                        .IsRequired()
                        .HasColumnType("TEXT")
                        .HasJsonPropertyName("difficulty");

                    b.Property<string>("Equipment")
                        .IsRequired()
                        .HasColumnType("TEXT")
                        .HasJsonPropertyName("equipment");

                    b.Property<string>("Force")
                        .IsRequired()
                        .HasColumnType("TEXT")
                        .HasJsonPropertyName("force");

                    b.Property<string>("GifUrl")
                        .IsRequired()
                        .HasColumnType("TEXT")
                        .HasJsonPropertyName("gifUrl");

                    b.PrimitiveCollection<string>("Instructions")
                        .IsRequired()
                        .HasColumnType("TEXT")
                        .HasJsonPropertyName("instructions");

                    b.Property<string>("IntensityLevel")
                        .IsRequired()
                        .HasColumnType("TEXT")
                        .HasJsonPropertyName("intensity_level");

                    b.Property<bool>("IsUnilateral")
                        .HasColumnType("INTEGER")
                        .HasJsonPropertyName("isUnilateral");

                    b.Property<string>("JointFocus")
                        .IsRequired()
                        .HasColumnType("TEXT")
                        .HasJsonPropertyName("joint_focus");

                    b.Property<string>("Mechanic")
                        .IsRequired()
                        .HasColumnType("TEXT")
                        .HasJsonPropertyName("mechanic");

                    b.Property<double>("Met")
                        .HasColumnType("REAL")
                        .HasJsonPropertyName("met");

                    b.PrimitiveCollection<string>("MovementTags")
                        .IsRequired()
                        .HasColumnType("TEXT")
                        .HasJsonPropertyName("movement_tags");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("TEXT")
                        .HasJsonPropertyName("name");

                    b.Property<int>("PopularityRank")
                        .HasColumnType("INTEGER")
                        .HasJsonPropertyName("popularityRank");

                    b.Property<string>("RecommendedReps")
                        .IsRequired()
                        .HasColumnType("TEXT")
                        .HasJsonPropertyName("recommendedReps");

                    b.Property<string>("RecommendedSets")
                        .IsRequired()
                        .HasColumnType("TEXT")
                        .HasJsonPropertyName("recommendedSets");

                    b.PrimitiveCollection<string>("SecondaryMuscles")
                        .IsRequired()
                        .HasColumnType("TEXT")
                        .HasJsonPropertyName("secondaryMuscles");

                    b.Property<string>("Target")
                        .IsRequired()
                        .HasColumnType("TEXT")
                        .HasJsonPropertyName("target");

                    b.HasKey("Id");

                    b.ToTable("Exercises");
                });

            modelBuilder.Entity("GymTracker.Core.Models.Workout", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.ToTable("Workouts");
                });

            modelBuilder.Entity("GymTracker.Core.Models.WorkoutExercise", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<string>("ExerciseId")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<int>("Reps")
                        .HasColumnType("INTEGER");

                    b.Property<int>("Sets")
                        .HasColumnType("INTEGER");

                    b.Property<double>("Weight")
                        .HasColumnType("REAL");

                    b.Property<int>("WorkoutId")
                        .HasColumnType("INTEGER");

                    b.HasKey("Id");

                    b.HasIndex("ExerciseId");

                    b.HasIndex("WorkoutId");

                    b.ToTable("WorkoutExercises");
                });

            modelBuilder.Entity("GymTracker.Core.Models.WorkoutExercise", b =>
                {
                    b.HasOne("GymTracker.Core.Models.Exercise", "Exercise")
                        .WithMany("WorkoutExercises")
                        .HasForeignKey("ExerciseId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("GymTracker.Core.Models.Workout", "Workout")
                        .WithMany("WorkoutExercises")
                        .HasForeignKey("WorkoutId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Exercise");

                    b.Navigation("Workout");
                });

            modelBuilder.Entity("GymTracker.Core.Models.Exercise", b =>
                {
                    b.Navigation("WorkoutExercises");
                });

            modelBuilder.Entity("GymTracker.Core.Models.Workout", b =>
                {
                    b.Navigation("WorkoutExercises");
                });
#pragma warning restore 612, 618
        }
    }
}
